language: julia
os:
- linux
julia:
- 1.2
notifications:
  email: false
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
jobs:
  allow_failures:
  - julia: nightly
  fast_finish: true
  include:
  - stage: Documentation
    julia: 1.2
    script: julia --project=docs -e ' using Pkg; Pkg.develop(PackageSpec(path=pwd()));
      Pkg.instantiate(); include("docs/make.jl");'
    after_success: skip
before_install:
- openssl aes-256-cbc -K $encrypted_70a6e0611c12_key -iv $encrypted_70a6e0611c12_iv
  -in github_deploy_key.enc -out github_deploy_key -d
